name: kafegama
description: KAFEGAMA Mobile App.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animated_splash_screen: ^1.3.0
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  curl_logger_dio_interceptor: ^0.0.3
  date_field: ^3.0.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_image_compress: ^1.1.1
  flutter_session_manager: ^1.0.3
  get: null
  google_fonts: ^2.1.0
  image_picker: ^0.8.6
  json_annotation: ^4.7.0
  lazy_load_scrollview: ^1.3.0
  material_design_icons_flutter: ^5.0.6996
  path_provider: ^2.0.1
  permission_handler: ^8.3.0
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audio/
    - assets/document/
    - assets/font/
    - assets/image/
    - assets/video/
